version: '3'
services:
  frontend:
    build: .
    image: mixnjuice/frontend:latest
    container_name: mixnjuice-frontend
    restart: always
    environment:
      VIRTUAL_HOST: ${FRONTEND_HOST}
      VIRTUAL_PORT: ${FRONTEND_PORT}
      LETSENCRYPT_HOST: ${FRONTEND_HOST}